{
  "openapi": "3.0.0",
  "info": {
    "title": "API Documentation",
    "description": "API Documentation for Bank Account",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://ivory-infinity-441116-s0.as.r.appspot.com/"
    }
  ],
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "tags": [
    {
      "name": "Auth"
    },
    {
      "name": "Users"
    },
    {
      "name": "BankAccount"
    },
    {
      "name": "Transaction"
    }
  ],
  "paths": {
    "/api/v1/auth/register": {
      "post": {
        "tags": ["Auth"],
        "summary": "Register User",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "name": "user3",
                  "email": "user3@gmail.com",
                  "password": "user3333",
                  "profile": {
                    "identityType": "KTP",
                    "identityNumber": "532434424324",
                    "address": "JL. address 3"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "headers": {
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sat, 09 Nov 2024 04:46:04 GMT"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "300"
                }
              },
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"12c-3b1eV0KUaff79+tZq4s9qt0MGx8\""
                }
              },
              "Via": {
                "schema": {
                  "type": "string",
                  "example": "1.1 google"
                }
              },
              "Alt-Svc": {
                "schema": {
                  "type": "string",
                  "example": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "User registered successfully",
                  "data": {
                    "id": 2,
                    "name": "user2",
                    "email": "user2@gmail.com",
                    "password": "$2b$10$pi8b7/yKfX.FwLeMh0vKPeNTvCT1AMRGQVm/h2kuGirUu9Acun2Ze",
                    "profile": {
                      "id": 2,
                      "identityType": "KTP",
                      "identityNumber": "5324324324",
                      "address": "JL. address 2",
                      "imageProfile": null,
                      "userId": 2
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/auth/login": {
      "post": {
        "tags": ["Auth"],
        "summary": "Login User",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "user2@gmail.com",
                  "password": "user2222"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sat, 09 Nov 2024 04:58:50 GMT"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Vary": {
                "schema": {
                  "type": "string",
                  "example": "Accept-Encoding"
                }
              },
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"d1-vPxlpkjX4F7FZTuJSCUfEf/yXMI\""
                }
              },
              "Content-Encoding": {
                "schema": {
                  "type": "string",
                  "example": "gzip"
                }
              },
              "Via": {
                "schema": {
                  "type": "string",
                  "example": "1.1 google"
                }
              },
              "Alt-Svc": {
                "schema": {
                  "type": "string",
                  "example": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"
                }
              },
              "Transfer-Encoding": {
                "schema": {
                  "type": "string",
                  "example": "chunked"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "status": "success",
                  "data": {
                    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ1c2VyMkBnbWFpbC5jb20iLCJuYW1lIjoidXNlcjIiLCJpYXQiOjE3MzExMjgzMzB9.jYjJyXBXbVEP-4O4Sttabb_vpJBu0_NaTb3qzFfEp2o"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/users": {
      "get": {
        "tags": ["Users"],
        "summary": "Get All Users",
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sat, 09 Nov 2024 04:48:24 GMT"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Vary": {
                "schema": {
                  "type": "string",
                  "example": "Accept-Encoding"
                }
              },
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"f9-7RLMG72CiQKMdbBIgbwo0f7mi6k\""
                }
              },
              "Content-Encoding": {
                "schema": {
                  "type": "string",
                  "example": "gzip"
                }
              },
              "Via": {
                "schema": {
                  "type": "string",
                  "example": "1.1 google"
                }
              },
              "Alt-Svc": {
                "schema": {
                  "type": "string",
                  "example": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"
                }
              },
              "Transfer-Encoding": {
                "schema": {
                  "type": "string",
                  "example": "chunked"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": [
                  {
                    "id": 1,
                    "name": "user1",
                    "email": "user1@gmail.com",
                    "password": "$2b$10$fHxDvifJFhypLd53bqhluuUc.RuMm4gpv/JcRmG3j9BxGDLDyRVqm"
                  },
                  {
                    "id": 2,
                    "name": "user2",
                    "email": "user2@gmail.com",
                    "password": "$2b$10$pi8b7/yKfX.FwLeMh0vKPeNTvCT1AMRGQVm/h2kuGirUu9Acun2Ze"
                  }
                ]
              }
            }
          }
        }
      }
    },
    "/api/v1/users/{id}": {
      "get": {
        "tags": ["Users"],
        "summary": "Get Users By Id",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sat, 09 Nov 2024 05:05:06 GMT"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Vary": {
                "schema": {
                  "type": "string",
                  "example": "Accept-Encoding"
                }
              },
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"fd-HwBfnmLWZlBSuQa0WXaKgfmdQmg\""
                }
              },
              "Content-Encoding": {
                "schema": {
                  "type": "string",
                  "example": "gzip"
                }
              },
              "Via": {
                "schema": {
                  "type": "string",
                  "example": "1.1 google"
                }
              },
              "Alt-Svc": {
                "schema": {
                  "type": "string",
                  "example": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"
                }
              },
              "Transfer-Encoding": {
                "schema": {
                  "type": "string",
                  "example": "chunked"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "id": 1,
                  "name": "user1",
                  "email": "user1@gmail.com",
                  "password": "$2b$10$fHxDvifJFhypLd53bqhluuUc.RuMm4gpv/JcRmG3j9BxGDLDyRVqm",
                  "profile": {
                    "id": 1,
                    "identityType": "KTP",
                    "identityNumber": "5324324324324",
                    "address": "JL. address 1",
                    "imageProfile": null,
                    "userId": 1
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": ["Users"],
        "summary": "Update Users",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "name": "user2 update",
                  "email": "user2@gmail.com",
                  "password": "user2222",
                  "profile": {
                    "identityType": "KTP",
                    "identityNumber": "5324324324",
                    "address": "JL. address 2"
                  }
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sat, 09 Nov 2024 05:09:49 GMT"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Vary": {
                "schema": {
                  "type": "string",
                  "example": "Accept-Encoding"
                }
              },
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"fc-DNQremPIK+IYNyycA74OSn+A65w\""
                }
              },
              "Content-Encoding": {
                "schema": {
                  "type": "string",
                  "example": "gzip"
                }
              },
              "Via": {
                "schema": {
                  "type": "string",
                  "example": "1.1 google"
                }
              },
              "Alt-Svc": {
                "schema": {
                  "type": "string",
                  "example": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"
                }
              },
              "Transfer-Encoding": {
                "schema": {
                  "type": "string",
                  "example": "chunked"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "User updated successfully",
                  "data": {
                    "id": 2,
                    "name": "user2 update",
                    "email": "user2@gmail.com",
                    "password": "user2222",
                    "profile": {
                      "id": 2,
                      "identityType": "KTP",
                      "identityNumber": "5324324324",
                      "address": "JL. address 2",
                      "imageProfile": null,
                      "userId": 2
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/users/{id}/image": {
      "put": {
        "tags": ["Users"],
        "summary": "Update User Profile Image",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "image": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sat, 09 Nov 2024 05:17:22 GMT"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Vary": {
                "schema": {
                  "type": "string",
                  "example": "Accept-Encoding"
                }
              },
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"ff-Tl7SjPrTPoT3MOckcfditXWMShU\""
                }
              },
              "Content-Encoding": {
                "schema": {
                  "type": "string",
                  "example": "gzip"
                }
              },
              "Via": {
                "schema": {
                  "type": "string",
                  "example": "1.1 google"
                }
              },
              "Alt-Svc": {
                "schema": {
                  "type": "string",
                  "example": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"
                }
              },
              "Transfer-Encoding": {
                "schema": {
                  "type": "string",
                  "example": "chunked"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "User image updated successfullyy",
                  "data": {
                    "id": 2,
                    "title": "updated photo profile user2 update",
                    "description": "successfully updated photo profile user2 update",
                    "url": "https://ik.imagekit.io/ysgre1dc1/user_images/user_2_1731129438846_KW0CR6AqA"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/accounts": {
      "post": {
        "tags": ["BankAccount"],
        "summary": "Create Bank Account",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "bankName": "Bank a",
                  "bankAccountNumber": "12345678912",
                  "balance": 1000,
                  "userId": 2
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "headers": {
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sat, 09 Nov 2024 05:27:03 GMT"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "143"
                }
              },
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"8f-S4IMhkpz/zlRroWD+dQH5/Fc5kI\""
                }
              },
              "Via": {
                "schema": {
                  "type": "string",
                  "example": "1.1 google"
                }
              },
              "Alt-Svc": {
                "schema": {
                  "type": "string",
                  "example": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Bank account created successfully",
                  "data": {
                    "id": 2,
                    "bankName": "Bank a",
                    "bankAccountNumber": "12345678911",
                    "balance": 1000,
                    "userId": 2
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": ["BankAccount"],
        "summary": "Get All Bank Account",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sat, 09 Nov 2024 05:28:14 GMT"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Vary": {
                "schema": {
                  "type": "string",
                  "example": "Accept-Encoding"
                }
              },
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"b3-9SL5ZuIkJz7cK8fDuSZfiFV3WLs\""
                }
              },
              "Content-Encoding": {
                "schema": {
                  "type": "string",
                  "example": "gzip"
                }
              },
              "Via": {
                "schema": {
                  "type": "string",
                  "example": "1.1 google"
                }
              },
              "Alt-Svc": {
                "schema": {
                  "type": "string",
                  "example": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"
                }
              },
              "Transfer-Encoding": {
                "schema": {
                  "type": "string",
                  "example": "chunked"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": [
                  {
                    "id": 1,
                    "bankName": "Bank a",
                    "bankAccountNumber": "12345678910",
                    "balance": 1000,
                    "userId": 1
                  },
                  {
                    "id": 2,
                    "bankName": "Bank a",
                    "bankAccountNumber": "12345678911",
                    "balance": 1000,
                    "userId": 2
                  }
                ]
              }
            }
          }
        }
      }
    },
    "/api/v1/accounts/{id}/deposit": {
      "post": {
        "tags": ["BankAccount"],
        "summary": "Deposit To Bank Account",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "balance": 500
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sat, 09 Nov 2024 05:44:29 GMT"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Vary": {
                "schema": {
                  "type": "string",
                  "example": "Accept-Encoding"
                }
              },
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"8f-2Oxf/7dKYG4fsRO+4F9NPe03zyM\""
                }
              },
              "Content-Encoding": {
                "schema": {
                  "type": "string",
                  "example": "gzip"
                }
              },
              "Via": {
                "schema": {
                  "type": "string",
                  "example": "1.1 google"
                }
              },
              "Alt-Svc": {
                "schema": {
                  "type": "string",
                  "example": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"
                }
              },
              "Transfer-Encoding": {
                "schema": {
                  "type": "string",
                  "example": "chunked"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Bank account deposit successfully",
                  "data": {
                    "id": 2,
                    "bankName": "bank a",
                    "bankAccountNumber": "12345678911",
                    "balance": 2000,
                    "userId": 2
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/accounts/{id}/withdraw": {
      "post": {
        "tags": ["BankAccount"],
        "summary": "Withdraw To Bank Account",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "balance": 500
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sat, 09 Nov 2024 05:47:42 GMT"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Vary": {
                "schema": {
                  "type": "string",
                  "example": "Accept-Encoding"
                }
              },
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"90-mf3m5Dr4cN7T+FOLxoe/yq0GPZM\""
                }
              },
              "Content-Encoding": {
                "schema": {
                  "type": "string",
                  "example": "gzip"
                }
              },
              "Via": {
                "schema": {
                  "type": "string",
                  "example": "1.1 google"
                }
              },
              "Alt-Svc": {
                "schema": {
                  "type": "string",
                  "example": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"
                }
              },
              "Transfer-Encoding": {
                "schema": {
                  "type": "string",
                  "example": "chunked"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Bank account withdraw successfully",
                  "data": {
                    "id": 2,
                    "bankName": "bank a",
                    "bankAccountNumber": "12345678911",
                    "balance": 1500,
                    "userId": 2
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/accounts/{id}": {
      "get": {
        "tags": ["BankAccount"],
        "summary": "Get Bank Account By Id",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sat, 09 Nov 2024 05:29:06 GMT"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Vary": {
                "schema": {
                  "type": "string",
                  "example": "Accept-Encoding"
                }
              },
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"d0-g+S4tq+FmdncTO4fmZl/n58Ri6c\""
                }
              },
              "Content-Encoding": {
                "schema": {
                  "type": "string",
                  "example": "gzip"
                }
              },
              "Via": {
                "schema": {
                  "type": "string",
                  "example": "1.1 google"
                }
              },
              "Alt-Svc": {
                "schema": {
                  "type": "string",
                  "example": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"
                }
              },
              "Transfer-Encoding": {
                "schema": {
                  "type": "string",
                  "example": "chunked"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "id": 2,
                  "bankName": "Bank a",
                  "bankAccountNumber": "12345678911",
                  "balance": 1000,
                  "userId": 2,
                  "user": {
                    "name": "user2 update",
                    "profile": {
                      "identityType": "KTP",
                      "identityNumber": "5324324324",
                      "address": "JL. address 2"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": ["BankAccount"],
        "summary": "Update Bank Account",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "bankName": "bank a",
                  "bankAccountNumber": "12345678911",
                  "balance": 1500,
                  "userId": 2
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sat, 09 Nov 2024 05:32:10 GMT"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Vary": {
                "schema": {
                  "type": "string",
                  "example": "Accept-Encoding"
                }
              },
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"8f-jvvPz1k1sZZyZdLn8TSJ7pprRcM\""
                }
              },
              "Content-Encoding": {
                "schema": {
                  "type": "string",
                  "example": "gzip"
                }
              },
              "Via": {
                "schema": {
                  "type": "string",
                  "example": "1.1 google"
                }
              },
              "Alt-Svc": {
                "schema": {
                  "type": "string",
                  "example": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"
                }
              },
              "Transfer-Encoding": {
                "schema": {
                  "type": "string",
                  "example": "chunked"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Bank account updated successfully",
                  "data": {
                    "id": 2,
                    "bankName": "bank a",
                    "bankAccountNumber": "12345678911",
                    "balance": 1500,
                    "userId": 2
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": ["BankAccount"],
        "summary": "Delete Bank Account",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sat, 09 Nov 2024 05:35:24 GMT"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Vary": {
                "schema": {
                  "type": "string",
                  "example": "Accept-Encoding"
                }
              },
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"8f-PsmbKFFmhtsuf3tZ1qmaxktvHFQ\""
                }
              },
              "Content-Encoding": {
                "schema": {
                  "type": "string",
                  "example": "gzip"
                }
              },
              "Via": {
                "schema": {
                  "type": "string",
                  "example": "1.1 google"
                }
              },
              "Alt-Svc": {
                "schema": {
                  "type": "string",
                  "example": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"
                }
              },
              "Transfer-Encoding": {
                "schema": {
                  "type": "string",
                  "example": "chunked"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Bank account deleted successfully",
                  "data": {
                    "id": 3,
                    "bankName": "Bank a",
                    "bankAccountNumber": "12345678912",
                    "balance": 1000,
                    "userId": 2
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/transactions": {
      "post": {
        "tags": ["Transaction"],
        "summary": "Create Transaction",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "sourceAccountId": 2,
                  "destinationAccountId": 1,
                  "amount": 500
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "headers": {
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sat, 09 Nov 2024 07:09:29 GMT"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "112"
                }
              },
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"70-GPuxMKiOY738t99QXJgF/iYWD/o\""
                }
              },
              "Via": {
                "schema": {
                  "type": "string",
                  "example": "1.1 google"
                }
              },
              "Alt-Svc": {
                "schema": {
                  "type": "string",
                  "example": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Transaction successfully",
                  "data": {
                    "id": 1,
                    "amount": 500,
                    "sourceAccountId": 1,
                    "destinationAccountId": 2
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": ["Transaction"],
        "summary": "Get All Transactions",
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sat, 09 Nov 2024 07:12:16 GMT"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Vary": {
                "schema": {
                  "type": "string",
                  "example": "Accept-Encoding"
                }
              },
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"44-19sCTRIx16gydUB9NH5bPODWGrk\""
                }
              },
              "Content-Encoding": {
                "schema": {
                  "type": "string",
                  "example": "gzip"
                }
              },
              "Via": {
                "schema": {
                  "type": "string",
                  "example": "1.1 google"
                }
              },
              "Alt-Svc": {
                "schema": {
                  "type": "string",
                  "example": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"
                }
              },
              "Transfer-Encoding": {
                "schema": {
                  "type": "string",
                  "example": "chunked"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": [
                  {
                    "id": 1,
                    "amount": 500,
                    "sourceAccountId": 1,
                    "destinationAccountId": 2
                  }
                ]
              }
            }
          }
        }
      }
    },
    "/api/v1/transactions/{id}": {
      "get": {
        "tags": ["Transaction"],
        "summary": "Get Transaction By Id",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sat, 09 Nov 2024 08:50:29 GMT"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Vary": {
                "schema": {
                  "type": "string",
                  "example": "Accept-Encoding"
                }
              },
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"118-t+if07CBbavfYednIv9/RkHCi/Q\""
                }
              },
              "Content-Encoding": {
                "schema": {
                  "type": "string",
                  "example": "gzip"
                }
              },
              "Via": {
                "schema": {
                  "type": "string",
                  "example": "1.1 google"
                }
              },
              "Alt-Svc": {
                "schema": {
                  "type": "string",
                  "example": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"
                }
              },
              "Transfer-Encoding": {
                "schema": {
                  "type": "string",
                  "example": "chunked"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "id": 1,
                  "amount": 500,
                  "sourceAccountId": 1,
                  "destinationAccountId": 2,
                  "sourceAccount": {
                    "id": 1,
                    "bankName": "Bank a",
                    "bankAccountNumber": "12345678910",
                    "balance": 500,
                    "userId": 1
                  },
                  "destinationAccount": {
                    "id": 2,
                    "bankName": "bank a",
                    "bankAccountNumber": "12345678911",
                    "balance": 2000,
                    "userId": 2
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
